### PR TITLE
Fixes an error being thrown when the format is not defined on a correction

### LINKED ISSUE #2092: Moderation review gives unexpected error
We received our first Circulars revision request.  But when I click on "Review", I get "Unexpected Error".  I tried logging out and back in, and the behavior remains.

### PR DESCRIPTION
**Pull request by dakota002**
Resolves #2092

### CODE REVIEW

File: app/routes/_gcn.circulars.moderation.$circularId.$requestor.tsx [hunk 1]
```diff
@@ -79,11 +80,16 @@ export default function () {
         oldString={circular.subject}
         newString={correction.subject}
       />
-      <h3>Format</h3>
-      <DiffedContent
-        oldString={circular.format ?? 'text/plain'}
-        newString={correction.format}
-      />
+
```
Comment (lpsinger) [inline app/routes/_gcn.circulars.moderation.$circularId.$requestor.tsx:83]:
```suggestion
```

**Review by lpsinger — CHANGES_REQUESTED** [review]
